language: node_js
node_js: stable

install: 
- rm -rf node_modules
- rm -rf package-lock.json
- npm cache clean --force
- npm uninstall hexo-generator-index --save

- npm install

before_install:
- export TZ='Asia/Shanghai'

script: 
- hexo clean
- hexo g

after_script: 
- cd ./public 
- git init 
- git config user.name "Travis-CI"
- git config user.email "Travis-CI@evobot.cn" 
- git add . 
- git commit -m "Update docs with TRAVIS-CI."
- git push --force --quiet "https://${github}@${GH_REF}" master:master
- git push --force "https://anycosmo@qq.com:${CO_TOKEN}@${CODING_REF}" master:coding-pages

# safelist
branches: 
  only: 
    - hexo

language: node_js
node_js: stable

git:
  depth: 1

env: 
  global: 
    # 使用https, 若使用ssh会出错
    - GH_REF: github.com/clikks/clikks.github.io.git
    - CODING_REF: e.coding.net/turbotig/turbotig.coding.me.git
