language: node_js
node_js: stable

branches:
  only:
    - hexo

cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K $encrypted_518a13a83897_key -iv $encrypted_518a13a83897_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo

install:
  - npm install # 安装 package.json 中的插件

script:
  - hexo generate

after_success:
  - git config --global user.name "clikks"
  - git config --global user.email "anycosmo@qq.com"
# - sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - hexo deploy
# E: Build LifeCycle
